# Generated by Django 4.0.4 on 2022-05-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoon_name', models.CharField(max_length=100)),
                ('episode_count', models.IntegerField()),
                ('date_finished', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cartoon_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FormTest.cartoonlist')),
            ],
        ),
    ]
