# Generated by Django 4.0.4 on 2022-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoon_name', models.CharField(max_length=100)),
                ('episode_count', models.IntegerField()),
                ('date_finished', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cartoon_list',
        ),
        migrations.DeleteModel(
            name='CartoonList',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
